version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    privileged: true
    ports:
      - "5672:5672"       # AMQP protocol port
      - "15672:15672"     # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - rabbitmq

  database-service:
    build:
      context: ./database-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - rabbitmq

  pdf-generator-service:
    build:
      context: ./pdf-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    volumes:
      - pdf_storage:/path/to/pdf
    depends_on:
      - rabbitmq

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    volumes:
      - pdf_storage:/path/to/pdf
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_log:
  pdf_storage: